name: Deploy WP Plugin to Cloudways

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip plugin folder
        run: |
          zip -r smart-search-control.zip . -x ".git/*" ".github/*" "node_modules/*" "*.zip" "package.json" README.md "package-lock.json" "debug.log"

      - name: Upload plugin to Cloudways via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CLOUDWAYS_HOST }}
          username: ${{ secrets.CLOUDWAYS_USER }}
          key: ${{ secrets.CLOUDWAYS_KEY }}
          port: ${{ secrets.CLOUDWAYS_PORT }}
          source: "smart-search-control.zip"
          target: "/home/master/applications/uwqreahejk/public_html/wp-content/plugins/"

      - name: Replace existing plugin and unzip
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.CLOUDWAYS_HOST }}
          username: ${{ secrets.CLOUDWAYS_USER }}
          key: ${{ secrets.CLOUDWAYS_KEY }}
          port: ${{ secrets.CLOUDWAYS_PORT }}
          script: |
            cd /home/master/applications/uwqreahejk/public_html/wp-content/plugins/
            PLUGIN_NAME="smart-search-control"
            # Remove existing plugin folder if exists
            rm -rf "$PLUGIN_NAME"
            # Create plugin directory
            mkdir "$PLUGIN_NAME"
            # Unzip the new plugin into the plugin directory
            unzip -o "$PLUGIN_NAME.zip" -d "$PLUGIN_NAME"
            # Remove the zip file
            rm -f "$PLUGIN_NAME.zip"

      - name: Clean up
        run: rm -f smart-search-control.zip
